GET http://localhost:3000/api

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Sabino Doe",
  "email": "sabino.doe@mail.com",
  "admin": true
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "sabino.doe@mail.com",
  "password": "senha123"
}

###

GET http://localhost:3000/users

###

GET http://localhost:3000/users/3

###

PATCH http://localhost:3000/users/3
Content-Type: application/json

{
  "name": "Antonio Sabino"
}

###

DELETE http://localhost:3000/users/1

###

POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "My first post",
  "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl vel ultricies lacinia, nunc nisl aliquet nisl, eget aliquam nisl nisl eu nunc.",
  "authorEmail": "sabino.doe@mail.com"
}

###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/1
