// swagger
GET http://localhost:3000/api

###
// create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Teste3",
  "email": "teste3@mail.com",
  "password": "teste3",
  "admin": true
}

###
// get a token
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "teste3@mail.com",
  "password": "teste3"
}

###
// get a profile
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RlMyIsImVtYWlsIjoidGVzdGUzQG1haWwuY29tIiwiaWF0IjoxNjY5OTkxMzk2LCJleHAiOjE2NzAwNzc3OTZ9._hoGcJS8K9RV2WfrPrMBfDNz6lGd8pVFIAcQgC5KnNE

###
// get all users
GET http://localhost:3000/users

###
// get a user
GET http://localhost:3000/users/3

###
// update a user
PATCH http://localhost:3000/users/3
Content-Type: application/json

{
  "name": "Antonio Sabino"
}

###
// delete a user
DELETE http://localhost:3000/users/1

